import type {
  Lead,
  Property,
  Appointment,
  Automation,
  Agent,
  DashboardStats,
  Activity,
} from "@/types";

// ─── Agents ───────────────────────────────────────────────────────────────────

export const DUMMY_AGENTS: Agent[] = [
  {
    id: "agent-1",
    name: "Sarah Mitchell",
    email: "sarah@aurexo.com",
    phone: "+971 50 123 4567",
    role: "manager",
    activeLeads: 24,
    closedDeals: 18,
    revenue: 2400000,
    joinedAt: "2023-01-15",
  },
  {
    id: "agent-2",
    name: "James Thornton",
    email: "james@aurexo.com",
    phone: "+971 55 987 6543",
    role: "agent",
    activeLeads: 15,
    closedDeals: 11,
    revenue: 1600000,
    joinedAt: "2023-03-20",
  },
  {
    id: "agent-3",
    name: "Layla Al Rashid",
    email: "layla@aurexo.com",
    phone: "+971 52 456 7890",
    role: "agent",
    activeLeads: 19,
    closedDeals: 9,
    revenue: 1100000,
    joinedAt: "2023-06-10",
  },
];

// ─── Leads ────────────────────────────────────────────────────────────────────

export const DUMMY_LEADS: Lead[] = [
  {
    id: "lead-1",
    name: "Ahmed Al Mansouri",
    email: "ahmed.mansouri@email.com",
    phone: "+971 50 111 2233",
    status: "qualified",
    source: "website",
    priority: "high",
    budget: 3500000,
    interestedIn: "Villa",
    location: "Palm Jumeirah, Dubai",
    notes: "Looking for a 4-bed villa with private pool. Flexible on move-in date.",
    assignedTo: "agent-1",
    createdAt: "2026-05-01T09:00:00Z",
    updatedAt: "2026-05-14T11:30:00Z",
    lastContactedAt: "2026-05-14T11:30:00Z",
    tags: ["VIP", "Cash Buyer", "Urgent"],
  },
  {
    id: "lead-2",
    name: "Priya Sharma",
    email: "priya.sharma@gmail.com",
    phone: "+971 55 234 5678",
    status: "new",
    source: "referral",
    priority: "medium",
    budget: 1200000,
    interestedIn: "Apartment",
    location: "Dubai Marina",
    notes: "First-time buyer. Interested in 2-bed apartment near metro.",
    assignedTo: "agent-2",
    createdAt: "2026-05-10T14:00:00Z",
    updatedAt: "2026-05-10T14:00:00Z",
    lastContactedAt: null,
    tags: ["First-time Buyer"],
  },
  {
    id: "lead-3",
    name: "Marcus Webb",
    email: "m.webb@investgroup.com",
    phone: "+44 207 123 4567",
    status: "proposal",
    source: "n8n-automation",
    priority: "high",
    budget: 8000000,
    interestedIn: "Penthouse",
    location: "Downtown Dubai",
    notes: "Investor looking for high-yield property. Prefers off-plan or ready units.",
    assignedTo: "agent-1",
    createdAt: "2026-04-28T08:00:00Z",
    updatedAt: "2026-05-12T16:45:00Z",
    lastContactedAt: "2026-05-12T16:45:00Z",
    tags: ["Investor", "High Value", "International"],
  },
  {
    id: "lead-4",
    name: "Fatima Al Zaabi",
    email: "fatima.zaabi@outlook.com",
    phone: "+971 56 345 6789",
    status: "contacted",
    source: "social",
    priority: "low",
    budget: 700000,
    interestedIn: "Townhouse",
    location: "Jumeirah Village Circle",
    notes: "Looking for family home. 3 kids. Good school proximity preferred.",
    assignedTo: "agent-3",
    createdAt: "2026-05-08T10:00:00Z",
    updatedAt: "2026-05-11T09:15:00Z",
    lastContactedAt: "2026-05-11T09:15:00Z",
    tags: ["Family"],
  },
  {
    id: "lead-5",
    name: "Oliver Chen",
    email: "oliver.chen@techstartup.io",
    phone: "+65 9123 4567",
    status: "won",
    source: "website",
    priority: "high",
    budget: 2100000,
    interestedIn: "Apartment",
    location: "Business Bay, Dubai",
    notes: "Closed deal on 2-bed unit. Very smooth transaction.",
    assignedTo: "agent-2",
    createdAt: "2026-04-15T09:00:00Z",
    updatedAt: "2026-05-05T14:00:00Z",
    lastContactedAt: "2026-05-05T14:00:00Z",
    tags: ["Closed", "Return Client"],
  },
  {
    id: "lead-6",
    name: "Nadia Kowalski",
    email: "nadia.k@europrop.eu",
    phone: "+48 22 123 4567",
    status: "lost",
    source: "cold-call",
    priority: "low",
    budget: 1800000,
    interestedIn: "Villa",
    location: "Arabian Ranches",
    notes: "Decided to invest in Portugal instead. Stay in touch for next cycle.",
    assignedTo: "agent-3",
    createdAt: "2026-04-01T11:00:00Z",
    updatedAt: "2026-04-30T10:00:00Z",
    lastContactedAt: "2026-04-30T10:00:00Z",
    tags: ["Cold"],
  },
  {
    id: "lead-7",
    name: "Rajan Mehta",
    email: "rajan.mehta@fingroup.in",
    phone: "+91 98765 43210",
    status: "new",
    source: "referral",
    priority: "medium",
    budget: 5000000,
    interestedIn: "Villa",
    location: "Emirates Hills",
    notes: "Referred by existing client. Looking for luxury villa.",
    assignedTo: "agent-1",
    createdAt: "2026-05-15T07:30:00Z",
    updatedAt: "2026-05-15T07:30:00Z",
    lastContactedAt: null,
    tags: ["Referral", "Luxury"],
  },
  {
    id: "lead-8",
    name: "Sophie Laurent",
    email: "s.laurent@paris.fr",
    phone: "+33 1 23 45 67 89",
    status: "qualified",
    source: "website",
    priority: "medium",
    budget: 1500000,
    interestedIn: "Apartment",
    location: "Bluewaters Island",
    notes: "Holiday home buyer. Wants sea view unit.",
    assignedTo: "agent-2",
    createdAt: "2026-05-03T13:00:00Z",
    updatedAt: "2026-05-13T10:00:00Z",
    lastContactedAt: "2026-05-13T10:00:00Z",
    tags: ["Holiday Home"],
  },
];

// ─── Properties ───────────────────────────────────────────────────────────────

export const DUMMY_PROPERTIES: Property[] = [
  {
    id: "prop-1",
    title: "Luxury 4-Bed Villa with Private Pool",
    type: "villa",
    status: "available",
    listingType: "sale",
    price: 4200000,
    area: 5800,
    bedrooms: 4,
    bathrooms: 5,
    location: "Palm Jumeirah, Dubai",
    address: "Frond M, Palm Jumeirah, Dubai, UAE",
    description: "Stunning beachfront villa with private pool and direct beach access.",
    features: ["Private Pool", "Beach Access", "Smart Home", "Maid's Room", "4-Car Garage"],
    images: [],
    agentId: "agent-1",
    createdAt: "2026-04-10T09:00:00Z",
    updatedAt: "2026-05-01T11:00:00Z",
  },
  {
    id: "prop-2",
    title: "Modern 2-Bed Apartment — Marina View",
    type: "apartment",
    status: "available",
    listingType: "sale",
    price: 1350000,
    area: 1250,
    bedrooms: 2,
    bathrooms: 2,
    location: "Dubai Marina",
    address: "Marina Gate Tower 2, Dubai Marina, UAE",
    description: "High-floor apartment with unobstructed marina and sea views.",
    features: ["Full Marina View", "Gym", "Pool", "Concierge", "Covered Parking"],
    images: [],
    agentId: "agent-2",
    createdAt: "2026-04-18T10:00:00Z",
    updatedAt: "2026-05-08T09:30:00Z",
  },
  {
    id: "prop-3",
    title: "Penthouse — Burj Khalifa View",
    type: "penthouse",
    status: "under-offer",
    listingType: "sale",
    price: 9500000,
    area: 7200,
    bedrooms: 5,
    bathrooms: 6,
    location: "Downtown Dubai",
    address: "The Address Sky View, Downtown Dubai, UAE",
    description: "Spectacular penthouse with panoramic Burj Khalifa and fountain views.",
    features: ["Private Terrace", "Burj View", "Private Elevator", "Rooftop Pool", "Smart Home"],
    images: [],
    agentId: "agent-1",
    createdAt: "2026-03-22T08:00:00Z",
    updatedAt: "2026-05-12T14:00:00Z",
  },
  {
    id: "prop-4",
    title: "3-Bed Townhouse — Family Community",
    type: "townhouse",
    status: "available",
    listingType: "sale",
    price: 1850000,
    area: 2900,
    bedrooms: 3,
    bathrooms: 4,
    location: "Arabian Ranches 3, Dubai",
    address: "Spring Community, Arabian Ranches 3, Dubai, UAE",
    description: "Corner townhouse in a lush, gated family community with park access.",
    features: ["Corner Unit", "Garden", "Community Pool", "Clubhouse", "Near School"],
    images: [],
    agentId: "agent-3",
    createdAt: "2026-04-25T11:00:00Z",
    updatedAt: "2026-05-10T10:00:00Z",
  },
  {
    id: "prop-5",
    title: "1-Bed Apartment — JVC",
    type: "apartment",
    status: "available",
    listingType: "rent",
    price: 65000,
    area: 750,
    bedrooms: 1,
    bathrooms: 1,
    location: "Jumeirah Village Circle",
    address: "Circle Mall Tower, JVC, Dubai, UAE",
    description: "Bright, fully furnished 1-bed apartment, ideal for young professionals.",
    features: ["Furnished", "Gym", "Pool", "Balcony", "Near Mall"],
    images: [],
    agentId: "agent-2",
    createdAt: "2026-05-01T09:00:00Z",
    updatedAt: "2026-05-01T09:00:00Z",
  },
  {
    id: "prop-6",
    title: "Commercial Office — DIFC",
    type: "commercial",
    status: "available",
    listingType: "rent",
    price: 320000,
    area: 3200,
    bedrooms: 0,
    bathrooms: 2,
    location: "DIFC, Dubai",
    address: "Gate Avenue, DIFC, Dubai, UAE",
    description: "Grade-A fitted office space in the heart of Dubai's financial hub.",
    features: ["Fully Fitted", "Meeting Rooms", "Reception", "24/7 Security", "Valet"],
    images: [],
    agentId: "agent-1",
    createdAt: "2026-04-30T10:00:00Z",
    updatedAt: "2026-05-09T12:00:00Z",
  },
];

// ─── Appointments ─────────────────────────────────────────────────────────────

export const DUMMY_APPOINTMENTS: Appointment[] = [
  {
    id: "apt-1",
    title: "Property Viewing — Palm Jumeirah Villa",
    type: "viewing",
    status: "confirmed",
    leadId: "lead-1",
    leadName: "Ahmed Al Mansouri",
    propertyId: "prop-1",
    propertyTitle: "Luxury 4-Bed Villa with Private Pool",
    agentId: "agent-1",
    agentName: "Sarah Mitchell",
    date: "2026-05-17",
    time: "10:00",
    duration: 60,
    location: "Frond M, Palm Jumeirah",
    notes: "Client prefers morning viewing. Bring price comparison sheet.",
    createdAt: "2026-05-14T11:00:00Z",
  },
  {
    id: "apt-2",
    title: "Initial Consultation — Marcus Webb",
    type: "consultation",
    status: "scheduled",
    leadId: "lead-3",
    leadName: "Marcus Webb",
    agentId: "agent-1",
    agentName: "Sarah Mitchell",
    date: "2026-05-18",
    time: "14:00",
    duration: 45,
    location: "Aurexo Office — DIFC",
    notes: "Video call via Zoom if client can't make it in person.",
    createdAt: "2026-05-13T09:00:00Z",
  },
  {
    id: "apt-3",
    title: "Follow-up — Priya Sharma",
    type: "follow-up",
    status: "scheduled",
    leadId: "lead-2",
    leadName: "Priya Sharma",
    agentId: "agent-2",
    agentName: "James Thornton",
    date: "2026-05-16",
    time: "11:30",
    duration: 30,
    location: "Phone Call",
    notes: "Check if she's ready to book a viewing.",
    createdAt: "2026-05-10T15:00:00Z",
  },
  {
    id: "apt-4",
    title: "Contract Signing — Oliver Chen",
    type: "signing",
    status: "completed",
    leadId: "lead-5",
    leadName: "Oliver Chen",
    propertyId: "prop-2",
    propertyTitle: "Modern 2-Bed Apartment — Marina View",
    agentId: "agent-2",
    agentName: "James Thornton",
    date: "2026-05-05",
    time: "15:00",
    duration: 90,
    location: "Aurexo Office — DIFC",
    notes: "Deal closed successfully. AED 2.1M sale.",
    createdAt: "2026-05-03T10:00:00Z",
  },
  {
    id: "apt-5",
    title: "Villa Viewing — Rajan Mehta",
    type: "viewing",
    status: "scheduled",
    leadId: "lead-7",
    leadName: "Rajan Mehta",
    propertyId: "prop-1",
    propertyTitle: "Luxury 4-Bed Villa with Private Pool",
    agentId: "agent-1",
    agentName: "Sarah Mitchell",
    date: "2026-05-19",
    time: "09:00",
    duration: 60,
    location: "Palm Jumeirah",
    notes: "New referral lead. Treat as VIP.",
    createdAt: "2026-05-15T08:00:00Z",
  },
];

// ─── Automations ──────────────────────────────────────────────────────────────

export const DUMMY_AUTOMATIONS: Automation[] = [
  {
    id: "auto-1",
    name: "New Lead Welcome Email",
    description: "Sends a personalized welcome email immediately when a new lead is captured.",
    trigger: "new-lead",
    actions: ["send-email", "notify-agent"],
    isActive: true,
    runCount: 142,
    lastRunAt: "2026-05-15T07:31:00Z",
    createdAt: "2026-03-01T09:00:00Z",
    n8nWebhookUrl: "http://localhost:5678/webhook/new-lead-email",
  },
  {
    id: "auto-2",
    name: "Appointment Reminder — 24hr",
    description: "Sends WhatsApp and email reminders to leads 24 hours before their appointment.",
    trigger: "appointment-reminder",
    actions: ["send-whatsapp", "send-email"],
    isActive: true,
    runCount: 87,
    lastRunAt: "2026-05-15T09:00:00Z",
    createdAt: "2026-03-05T10:00:00Z",
    n8nWebhookUrl: "http://localhost:5678/webhook/appointment-reminder",
  },
  {
    id: "auto-3",
    name: "Follow-up Sequence — Unresponsive Leads",
    description: "Triggers a 3-step follow-up sequence for leads with no response in 48 hours.",
    trigger: "follow-up-due",
    actions: ["send-email", "send-whatsapp", "create-task"],
    isActive: true,
    runCount: 56,
    lastRunAt: "2026-05-14T14:00:00Z",
    createdAt: "2026-03-10T11:00:00Z",
    n8nWebhookUrl: "http://localhost:5678/webhook/follow-up-sequence",
  },
  {
    id: "auto-4",
    name: "Property Match Alert",
    description: "Notifies matching leads when a new property matching their criteria is listed.",
    trigger: "property-matched",
    actions: ["send-email", "notify-agent"],
    isActive: false,
    runCount: 23,
    lastRunAt: "2026-05-01T10:00:00Z",
    createdAt: "2026-03-15T09:00:00Z",
    n8nWebhookUrl: "http://localhost:5678/webhook/property-match",
  },
  {
    id: "auto-5",
    name: "Lead Status Change Notification",
    description: "Alerts the assigned agent via Slack/WhatsApp when a lead's status changes.",
    trigger: "lead-status-changed",
    actions: ["notify-agent", "update-lead"],
    isActive: true,
    runCount: 201,
    lastRunAt: "2026-05-15T11:15:00Z",
    createdAt: "2026-02-20T09:00:00Z",
  },
  {
    id: "auto-6",
    name: "Website Form → CRM",
    description: "Auto-captures leads from the website contact form and creates CRM records.",
    trigger: "form-submitted",
    actions: ["update-lead", "send-email", "notify-agent"],
    isActive: true,
    runCount: 318,
    lastRunAt: "2026-05-15T12:40:00Z",
    createdAt: "2026-02-01T08:00:00Z",
    n8nWebhookUrl: "http://localhost:5678/webhook/form-capture",
  },
];

// ─── Dashboard Stats ──────────────────────────────────────────────────────────

export const DUMMY_STATS: DashboardStats = {
  totalLeads: 248,
  leadsGrowth: 12.5,
  activeProperties: 34,
  propertiesGrowth: 8.3,
  appointmentsThisWeek: 18,
  appointmentsGrowth: -2.1,
  revenueThisMonth: 4750000,
  revenueGrowth: 23.7,
  conversionRate: 18.4,
  automationRuns: 827,
};

// ─── Activity Feed ────────────────────────────────────────────────────────────

export const DUMMY_ACTIVITIES: Activity[] = [
  {
    id: "act-1",
    type: "lead_created",
    title: "New lead captured",
    description: "Rajan Mehta added via referral — Emirates Hills Villa inquiry",
    agentName: "Sarah Mitchell",
    createdAt: "2026-05-15T07:30:00Z",
  },
  {
    id: "act-2",
    type: "automation_run",
    title: "Automation triggered",
    description: "Welcome email sent to Rajan Mehta via n8n workflow",
    agentName: "System",
    createdAt: "2026-05-15T07:31:00Z",
  },
  {
    id: "act-3",
    type: "appointment_booked",
    title: "Viewing scheduled",
    description: "Ahmed Al Mansouri — Palm Jumeirah Villa viewing on May 17",
    agentName: "Sarah Mitchell",
    createdAt: "2026-05-14T11:00:00Z",
  },
  {
    id: "act-4",
    type: "lead_updated",
    title: "Lead moved to Proposal",
    description: "Marcus Webb advanced to proposal stage — Penthouse Downtown",
    agentName: "Sarah Mitchell",
    createdAt: "2026-05-12T16:45:00Z",
  },
  {
    id: "act-5",
    type: "deal_closed",
    title: "Deal closed",
    description: "Oliver Chen — Business Bay Apartment sold for AED 2,100,000",
    agentName: "James Thornton",
    createdAt: "2026-05-05T14:00:00Z",
  },
  {
    id: "act-6",
    type: "property_added",
    title: "Property listed",
    description: "New commercial office listing added — DIFC, AED 320,000/yr",
    agentName: "Sarah Mitchell",
    createdAt: "2026-04-30T10:00:00Z",
  },
];
